name: Bug report
description: Report a bug
title: "[v<replace_this_with_your_tweak_version>] <replace_this_with_your_title>"
labels: bug

body:

- type: checkboxes
  attributes:
    label: Have you checked existing issues?
    description: _**⚠️ IMPORTANT:** Please review existing [issues](https://github.com/therealFoxster/DontEatMyContent/issues) before filing this report. You might find workarounds/solutions to the issue you're facing there too! Duplicated issues will be closed without further explanation._
    options:
    - label: Yes, I checked existing issues.
      required: true

- type: input
  attributes:
    label: iOS/iPadOS version
    description:
    placeholder: e.g., iOS 18.5
  validations:
    required: true

- type: input
  attributes:
    label: YouTube app version
    description:
    placeholder: e.g., 19.21.3
  validations:
    required: true

- type: input
  id: tweak_version
  attributes:
    label: DontEatMyContent version
    description:
    placeholder: e.g., 1.1.10
  validations:
    required: true

- type: textarea
  attributes:
    label: IPA source
    description: How did you get the YouTube IPA?
  validations:
    required: true

- type: textarea
  attributes:
    label: Description
    description: Describe the issue
  validations:
    required: true

- type: textarea
  attributes:
    label: Steps to reproduce
    description: Please attach videos or screenshots if possible
    value: |
        1. 
        2. 
  validations:
    required: true

- type: textarea
  id: logs
  attributes:
    label: Crash log
    description: If the app crashes, **please provide the crash log**. It can be found in Settings > Privacy > Analytics & Improvements > Analytics Data > Youtube-xxx-xxx.ips
    render: shell

- type: textarea
  attributes:
    label: Additional information
  validations:
    required: false
