name: Build DontEatMyContent

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'
      - '.github/**'
      - control
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout DontEatMyContent
      uses: actions/checkout@v4.1.7
      with:
        submodules: recursive

    - name: Checkout Theos
      uses: actions/checkout@v4.1.7
      with:
        repository: theos/theos
        ref: master
        path: theos
        submodules: recursive

    - name: Install dependencies
      run: |
        brew install ldid
        # bash -c "$(curl -fsSL https://raw.githubusercontent.com/roothide/theos/master/bin/install-theos)"

    - name: Build
      run: |
        make package FINALPACKAGE=1
        make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
        # make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=roothide
        PACKAGES=$(ls packages/ | grep .deb)
        if [ -z "$PACKAGES" ]; then
          echo "No packages found."
          exit 1
        fi
      env:
        THEOS: ${{ github.workspace }}/theos

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Packages
        path: packages/